app:
  maintainer: maintainer
  slackChannel: channel
  repository: "https://github.com/BedeGaming/gitsourcetest"

container:
  repository: some.repo
  pullPolicy: Always

deployment: {}

service:
  enabled: true
  name: http
  protocol: TCP

ingress:
  enabled: true
  sslRedirectEnabled: false
  enableCors: "true"

secretName: "secret"

tolerateSpot: "true"
spotEnabled: "true"
